version: "3.1"

services:
  mongo_db:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always

  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
